name: Mingstagram CI / CD

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ghcr.io
  GITHUB_USER_NAME: ${{ secrets.USER_NAME }}
  DOCKER_FILE_PATH: ./Dockerfile
  DOCKER_CONTAINER_NAME: mingstagram
  IMAGE_NAME: ghcr.io/${{ github.repository }}/main
  PROJECT_NAME: mingstagram

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set Gradle Permission
      run: chmod +x ./gradlew

    - name: Gradle Build
      run: ./gradlew clean bootJar -x test

        #################### GITHUB CONTAINER REGISTRY LOGIN ########################

    - name: Login to Github Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ env.GITHUB_USER_NAME }}
        password: ${{ secrets.ACCOUNT_TOKEN }}

        #################### DOCKER BUILD AND PUSH ###############################

    - name: Build Push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ${{ env.DOCKER_FILE_PATH }}
        tags: ${{ env.IMAGE_NAME }}:latest
        no-cache: true
        push: true

    ######################## DEPLOY ################################

  deploy:
    name: Snaps CD with Docker
    needs: build
    runs-on: self-hosted

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ env.GITHUB_USER_NAME }}
          password: ${{ secrets.ACCOUNT_TOKEN }}

      - name: Docker Pull & Run
        run: |
          docker rmi -f ${{ env.IMAGE_NAME }}
          docker rm -f ${{ env.DOCKER_CONTAINER_NAME }}
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker run -p 8080:8080 -d --name ${{ env.DOCKER_CONTAINER_NAME }} ${{ env.IMAGE_NAME }}